name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
- type: markdown
  attributes:
    value: |      
      > Please search to see if an issue already exists for the bug you encountered.
      
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: Description...
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction steps
    description: Steps to reproduce the behavior. Please walk us through it step by step.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  id: aditional-info
  attributes:
    label: Aditional info
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      ***Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.*
    placeholder: Optional aditional info...
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](name: Feature Request
description: Suggest a new feature or enhancemets for this project
labels: [enhancement]
body:
- type: textarea
  id: feature-description
  attributes:
    label: Description
    description: |
      Describe the new feature or enhancements you'd like to see.
    placeholder: Feature or enhancement description...
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
).
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
