name: Feature Request
description: Suggest a new feature or enhancemets for this project
labels: [enhancement]
body:
- type: textarea
  id: feature-description
  attributes:
    label: Description
    description: |
      Describe the new feature or enhancements you'd like to see.
    placeholder: Feature or enhancement description...
  validations:
    required: true
