// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKl1e5UEWKl1j4CrCKENTHhKO8-XWCHfg',
    appId: '1:787552385461:web:900c05d7826287726501fc',
    messagingSenderId: '787552385461',
    projectId: 'notesproject-ab12c',
    authDomain: 'notesproject-ab12c.firebaseapp.com',
    databaseURL: 'https://notesproject-ab12c.firebaseio.com',
    storageBucket: 'notesproject-ab12c.appspot.com',
    measurementId: 'G-PZZ7F85GVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW9K-7GwxfxbqZUArRyAx7M0fM5XC-edU',
    appId: '1:787552385461:android:6eee430d3a3362316501fc',
    messagingSenderId: '787552385461',
    projectId: 'notesproject-ab12c',
    databaseURL: 'https://notesproject-ab12c.firebaseio.com',
    storageBucket: 'notesproject-ab12c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2vg3-U-w-keue8E-1FQL4qI69l93qB4',
    appId: '1:787552385461:ios:1ec75293fb95a9446501fc',
    messagingSenderId: '787552385461',
    projectId: 'notesproject-ab12c',
    databaseURL: 'https://notesproject-ab12c.firebaseio.com',
    storageBucket: 'notesproject-ab12c.appspot.com',
    androidClientId: '787552385461-unrffto1s4r79293qomcag80f3km03fv.apps.googleusercontent.com',
    iosClientId: '787552385461-bkl07ddvad16kpr96vkmc4e8vl9jj9kv.apps.googleusercontent.com',
    iosBundleId: 'com.fermod.flutterNotes',
  );
}
