name: Draft Release
on:
  workflow_dispatch:
    # Enable manual workflow run
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events that match "*". For example: "1.0", "20.15.10"

jobs:
  draft-release:
    name: Create draft release
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Flutter Notes v${{ github.ref }}
          draft: true
          prerelease: false

  build:
    name: Create ${{ matrix.target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [Android, Web] # [Android, iOS, Linux, macOS, Windows, Web]
        include:
          - os: ubuntu-20.04
            target: Android
            build_target: apk
            build_path: build/app/outputs/apk/release
            asset_extension: .apk
            asset_content_type: application/vnd.android.package-archive
            channel: stable
          # - os: ubuntu-20.04
          #   target: Linux
          #   build_target: linux
          #   build_path: build/linux/release/bundle
          #   asset_extension: .tar.gz
          #   asset_content_type: application/gzip
          #   channel: stable
          # - os: macos-10.15
          #   target: macOS
          #   build_target: macos
          #   build_path: build/macos/Build/Products/Release
          #   asset_extension: .zip
          #   asset_content_type: application/zip
          #   channel: stable
          # - os: windows-2019
          #   target: windows
          #   build_target: windows
          #   build_path: build/windows/runner/Release
          #   asset_extension: .zip
          #   asset_content_type: application/zip
          #   channel: stable
          - os: ubuntu-20.04
            target: Web
            build_target: web
            build_path: build/web
            asset_extension: .tar.gz
            asset_content_type: application/gzip
            channel: stable
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
    needs: draft-release
    steps:
      # Set up Flutter and add it to the path.
      - name: Clone Flutter repository with ${{ matrix.channel }} channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: ${{ matrix.channel }}

      # Set up required dependencies.
      - name: Install Linux dependencies
        if: matrix.build_target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
      - name: Install Android dependencies
        if: matrix.build_target == 'android'
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Enable web support
        if: matrix.build_target == 'web'
        run: flutter config --enable-web
      - name: Enable ${{ matrix.target }} desktop support
        if: matrix.build_target == 'linux' || matrix.build_target == 'windows' || matrix.build_target == 'macos'
        run: flutter config --enable-${{ matrix.build_target }}-desktop
      - name: Run Flutter doctor
        run: flutter doctor -v

      # Clone the repository and get required packages.
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Get packages for the Flutter project
        run: flutter pub get

      # Build the application.
      - name: Build project
        run: flutter build -v ${{ matrix.build_target }} --release

      # Prepare release build package.
      - name: Copy VC redistributables to release directory for Windows
        if: matrix.build_target == 'windows'
        run: |
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\msvcp140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140.dll') .
          Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\vcruntime140_1.dll') .

      # Compress build.
      - name: Compress build for Windows
        if: matrix.build_target == 'windows'
        run: compress-archive -Path * -DestinationPath ./flutter_notes_${{ matrix.build_target }}${{ matrix.asset_extension }}
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for Linux
        if: matrix.build_target == 'linux' || matrix.build_target == 'web'
        run: tar czf ./flutter_notes_${{ matrix.build_target }}${{ matrix.asset_extension }} *
        working-directory: ${{ matrix.build_path }}
      - name: Compress build for macOS
        if: matrix.build_target == 'macos'
        run: ditto -c -k --sequesterRsrc --keepParent Flutter\ Notes.app ./flutter_notes_${{ matrix.build_target }}${{ matrix.asset_extension }}
        working-directory: ${{ matrix.build_path }}
      - name: Rename build for Android
        if: matrix.build_target == 'apk'
        run: mv app-release${{ matrix.asset_extension }} ./flutter_notes_${{ matrix.build_target }}${{ matrix.asset_extension }}
        working-directory: ${{ matrix.build_path }}

      # Upload the build.
      - name: Get release tag version
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.draft-release.outputs.upload_url }}
          asset_path: ./${{ matrix.build_path }}/flutter_notes_${{ matrix.build_target }}${{ matrix.asset_extension }}
          asset_name: flutter_notes_${{ matrix.build_target }}_${{ env.RELEASE_TAG }}${{ matrix.asset_extension }}
          asset_content_type: ${{ matrix.asset_content_type }}
