name: Unit Tests
on:
  push:
    branches:
      - main
      - FerMod*
  pull_request:
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      # Set up Flutter and add it to the path.
      - name: Clone Flutter repository with master channel
        uses: actions/checkout@v2
        with:
          repository: "flutter/flutter"
          ref: "master"
          path: "flutter"
          fetch-depth: 0
      - name: Add Flutter to the PATH for Unix
        if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os, 'ubuntu')
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
      - name: Add Flutter to the PATH for Windows
        if: startsWith(matrix.os, 'windows')
        run: echo "${env:GITHUB_WORKSPACE}\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Run Flutter doctor
        run: flutter doctor -v

      # Clone the repository under 'code', to avoid conflicts with 'flutter'.
      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          path: "code"

      # Run the tests for the repository.
      - name: Get packages for the Flutter project
        run: flutter pub get
        working-directory: code
      - name: Analyze the project's Dart code
        run: flutter analyze
        working-directory: code
      - name: Ensure the Dart code is formatted correctly
        run: flutter format --set-exit-if-changed --dry-run .
        working-directory: code
      - name: Enable build on web
        run: flutter config --enable-web
        working-directory: code
      - name: Run Flutter unit tests
        run: flutter test
        working-directory: code
